### Задание №1
Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [1]:
def puzir(arr):
    length = len(arr)
    for i in range(length-1):
        for j in range(length-i-1):
            if arr[j] < arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr


def max_per(arr):
    length = len(arr)
    for i in range(length-2):
        if arr[i]+arr[i+1] > arr[i+2] and arr[i]+arr[i+2] > arr[i+1] and arr[i+2]+arr[i+1] > arr[i]:
            per = arr[i] + arr[i+1] + arr[i+2]
            return per
    return 0

arr = [2, 1, 2]
print(max_per(arr))

5


### Задание №2
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [1]:
import numpy
from copy import deepcopy


def biggest_first_number(row):
    ans_row = deepcopy(row)

    max = -3
    for i in range(len(row)):
        if ans_row[i][0] >= max:
            max = ans_row[i][0]
    for i in range(len(row)):
        if ans_row[i][0] != max and ans_row[i][0] >= 0:
            ans_row[i][0] = -2
    return ans_row


def add_best_numbers(row, original_row):
    big_number = ''
    isNeededToBeChecked = False

    for i in range(len(row)):
        if row[i][0] >= 0:  
            if len(row[i]) == 1:
                big_number += str(''.join(map(str, original_row[i])))
                row[i][0] = -1
            else:
                row[i].__delitem__(0)
                isNeededToBeChecked = True

    length = len(row)
    i = 0
    while i < length:  # удаляем добавленные числа
        if row[i][0] == -1:
            original_row.__delitem__(i)
            row.__delitem__(i)
            length -= 1
        else:
            i += 1

    if isNeededToBeChecked:
        best_numbers = biggest_first_number(row)
        big_number += add_best_numbers(best_numbers, original_row)
    return big_number


def find_max(row):
    length = len(row)
    big_number = ''

    raw_row = [''] * length

    for i in range(length):
        number = str(row[i])  # превращаем наши числа в массив символов
        raw_row[i] = list(number)  # записываем наш массив в массив
        raw_row[i] = [int(raw_row[i]) for raw_row[i] in raw_row[i]]

    while len(raw_row) != 0:
        best_numbers = biggest_first_number(raw_row)  # находим лучших кандидатов

        big_number += add_best_numbers(best_numbers, raw_row)

    return big_number

row = numpy.random.randint(1, 150, size=5)
print(row)
result = find_max(row)
print(result)

[130  51   4 121  39]
51439130121
[2432, 24323]
243224323


### Задание №3
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [4]:
import numpy

def sort_matrix(mat):
    height = len(mat)
    width = len(mat[0])

    for x_start in range(1, width):
        line = []
        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            line.append(mat[y][x])
            x += 1
        #print(line)
        line.sort()
        #print(line)

        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            mat[y][x] = line[y]
            x += 1

    for y_start in range(0, height):
        line = []
        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            line.append(mat[y][x])
            y += 1
        #print(line)
        line.sort()
        #print(line)

        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            mat[y][x] = line[x]
            y += 1
            
            
matrix = numpy.random.randint(0, 10, size=(5,4))
print(matrix)

sort_matrix(matrix)
print(matrix)

[[3 9 2 2]
 [2 8 5 5]
 [8 4 8 8]
 [0 8 3 4]
 [0 8 4 0]]
[[3 5 2 2]
 [0 4 8 5]
 [4 2 8 9]
 [0 8 3 8]
 [0 8 8 4]]
